// pi-core: .pi/extensions/prepush-gate.ts GateStep gateSteps goRoots makeTargetDefined skipRequested isPushCommand
// Generated by scripts/check_claude_mods_drift.sh --write from the pi source
// above. Do not edit here: change pi, then regenerate.

export interface GateStep {
	name: string;
	cmd: string;
	args: string[];
	timeoutMs: number;
}

/** Pure: the prepush gate chain for a Go repo (ailang's gates, fast subset). */
export function gateSteps(): { name: string; cmd: string; args: string[]; timeoutMs: number }[] {
	return [
		{ name: "gofmt", cmd: "gofmt", args: ["-l", "cmd", "internal"], timeoutMs: 15_000 },
		{ name: "lint", cmd: "make", args: ["lint"], timeoutMs: 180_000 },
		{ name: "file-sizes", cmd: "make", args: ["check-file-sizes"], timeoutMs: 15_000 },
	];
}

/** Pure: the Go source roots (of cmd/, internal/) that `git ls-files` output touches. */
export function goRoots(lsFilesStdout: string): string[] {
	const files = lsFilesStdout.split("\n").filter((l) => l.trim() !== "");
	return ["cmd", "internal"].filter((root) => files.some((f) => f.startsWith(`${root}/`)));
}

/**
 * Pure: given `make -n <target>`'s result, does the repo define the target?
 * Only the two "it isn't there" shapes count as absent; any other failure
 * means the target exists and is broken, so the gate still runs (and blocks).
 */
export function makeTargetDefined(target: string, code: number, output: string): boolean {
	if (code === 0) return true;
	if (/No targets specified and no makefile found/i.test(output)) return false;
	const noRule = new RegExp(`No rule to make target [\`'"‘]${target.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}['"’]`);
	return !noRule.test(output);
}

/** Pure: is the operator-level escape hatch set in pi's own environment? */
export function skipRequested(env: Record<string, string | undefined>): boolean {
	return env.AILANG_SKIP_PREPUSH === "1";
}

/** Pure: does this bash command push to a remote? */
export function isPushCommand(command: string | undefined): boolean {
	if (!command) return false;
	return /\bgit push\b/.test(command) || /\bgh pr (create|merge)\b/.test(command);
}
